#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustClimbTrial.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="JustClimb")]
	public partial class JustClimbAppDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAgeGroup(AgeGroup instance);
    partial void UpdateAgeGroup(AgeGroup instance);
    partial void DeleteAgeGroup(AgeGroup instance);
    partial void InsertBoulderRoute(BoulderRoute instance);
    partial void UpdateBoulderRoute(BoulderRoute instance);
    partial void DeleteBoulderRoute(BoulderRoute instance);
    partial void InsertBoulderRouteVideo(BoulderRouteVideo instance);
    partial void UpdateBoulderRouteVideo(BoulderRouteVideo instance);
    partial void DeleteBoulderRouteVideo(BoulderRouteVideo instance);
    partial void InsertRock(Rock instance);
    partial void UpdateRock(Rock instance);
    partial void DeleteRock(Rock instance);
    partial void InsertRockOnBoulderRoute(RockOnBoulderRoute instance);
    partial void UpdateRockOnBoulderRoute(RockOnBoulderRoute instance);
    partial void DeleteRockOnBoulderRoute(RockOnBoulderRoute instance);
    partial void InsertRockOnTrainingRoute(RockOnTrainingRoute instance);
    partial void UpdateRockOnTrainingRoute(RockOnTrainingRoute instance);
    partial void DeleteRockOnTrainingRoute(RockOnTrainingRoute instance);
    partial void InsertRouteDifficulty(RouteDifficulty instance);
    partial void UpdateRouteDifficulty(RouteDifficulty instance);
    partial void DeleteRouteDifficulty(RouteDifficulty instance);
    partial void InsertTrainingRoute(TrainingRoute instance);
    partial void UpdateTrainingRoute(TrainingRoute instance);
    partial void DeleteTrainingRoute(TrainingRoute instance);
    partial void InsertTrainingRouteVideo(TrainingRouteVideo instance);
    partial void UpdateTrainingRouteVideo(TrainingRouteVideo instance);
    partial void DeleteTrainingRouteVideo(TrainingRouteVideo instance);
    partial void InsertWall(Wall instance);
    partial void UpdateWall(Wall instance);
    partial void DeleteWall(Wall instance);
    #endregion
		
		public JustClimbAppDataContext() : 
				base(global::JustClimbTrial.Properties.Settings.Default.JustClimbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public JustClimbAppDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JustClimbAppDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JustClimbAppDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JustClimbAppDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AgeGroup> AgeGroups
		{
			get
			{
				return this.GetTable<AgeGroup>();
			}
		}
		
		public System.Data.Linq.Table<BoulderRoute> BoulderRoutes
		{
			get
			{
				return this.GetTable<BoulderRoute>();
			}
		}
		
		public System.Data.Linq.Table<BoulderRouteVideo> BoulderRouteVideos
		{
			get
			{
				return this.GetTable<BoulderRouteVideo>();
			}
		}
		
		public System.Data.Linq.Table<Rock> Rocks
		{
			get
			{
				return this.GetTable<Rock>();
			}
		}
		
		public System.Data.Linq.Table<RockOnBoulderRoute> RockOnBoulderRoutes
		{
			get
			{
				return this.GetTable<RockOnBoulderRoute>();
			}
		}
		
		public System.Data.Linq.Table<RockOnTrainingRoute> RockOnTrainingRoutes
		{
			get
			{
				return this.GetTable<RockOnTrainingRoute>();
			}
		}
		
		public System.Data.Linq.Table<RouteDifficulty> RouteDifficulties
		{
			get
			{
				return this.GetTable<RouteDifficulty>();
			}
		}
		
		public System.Data.Linq.Table<TrainingRoute> TrainingRoutes
		{
			get
			{
				return this.GetTable<TrainingRoute>();
			}
		}
		
		public System.Data.Linq.Table<TrainingRouteVideo> TrainingRouteVideos
		{
			get
			{
				return this.GetTable<TrainingRouteVideo>();
			}
		}
		
		public System.Data.Linq.Table<Wall> Walls
		{
			get
			{
				return this.GetTable<Wall>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AgeGroup")]
	public partial class AgeGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AgeGroupID;
		
		private string _AgeDesc;
		
		private System.Nullable<bool> _IsValid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAgeGroupIDChanging(string value);
    partial void OnAgeGroupIDChanged();
    partial void OnAgeDescChanging(string value);
    partial void OnAgeDescChanged();
    partial void OnIsValidChanging(System.Nullable<bool> value);
    partial void OnIsValidChanged();
    #endregion
		
		public AgeGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroupID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AgeGroupID
		{
			get
			{
				return this._AgeGroupID;
			}
			set
			{
				if ((this._AgeGroupID != value))
				{
					this.OnAgeGroupIDChanging(value);
					this.SendPropertyChanging();
					this._AgeGroupID = value;
					this.SendPropertyChanged("AgeGroupID");
					this.OnAgeGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeDesc", DbType="NVarChar(20)")]
		public string AgeDesc
		{
			get
			{
				return this._AgeDesc;
			}
			set
			{
				if ((this._AgeDesc != value))
				{
					this.OnAgeDescChanging(value);
					this.SendPropertyChanging();
					this._AgeDesc = value;
					this.SendPropertyChanged("AgeDesc");
					this.OnAgeDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsValid", DbType="Bit")]
		public System.Nullable<bool> IsValid
		{
			get
			{
				return this._IsValid;
			}
			set
			{
				if ((this._IsValid != value))
				{
					this.OnIsValidChanging(value);
					this.SendPropertyChanging();
					this._IsValid = value;
					this.SendPropertyChanged("IsValid");
					this.OnIsValidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoulderRoute")]
	public partial class BoulderRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RouteID;
		
		private string _RouteNo;
		
		private string _Difficulty;
		
		private string _AgeGroup;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
		private string _Wall;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRouteIDChanging(string value);
    partial void OnRouteIDChanged();
    partial void OnRouteNoChanging(string value);
    partial void OnRouteNoChanged();
    partial void OnDifficultyChanging(string value);
    partial void OnDifficultyChanged();
    partial void OnAgeGroupChanging(string value);
    partial void OnAgeGroupChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    partial void OnWallChanging(string value);
    partial void OnWallChanged();
    #endregion
		
		public BoulderRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteNo", DbType="VarChar(20)")]
		public string RouteNo
		{
			get
			{
				return this._RouteNo;
			}
			set
			{
				if ((this._RouteNo != value))
				{
					this.OnRouteNoChanging(value);
					this.SendPropertyChanging();
					this._RouteNo = value;
					this.SendPropertyChanged("RouteNo");
					this.OnRouteNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="VarChar(20)")]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this.OnDifficultyChanging(value);
					this.SendPropertyChanging();
					this._Difficulty = value;
					this.SendPropertyChanged("Difficulty");
					this.OnDifficultyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(20)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this.OnAgeGroupChanging(value);
					this.SendPropertyChanging();
					this._AgeGroup = value;
					this.SendPropertyChanged("AgeGroup");
					this.OnAgeGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wall", DbType="VarChar(20)")]
		public string Wall
		{
			get
			{
				return this._Wall;
			}
			set
			{
				if ((this._Wall != value))
				{
					this.OnWallChanging(value);
					this.SendPropertyChanging();
					this._Wall = value;
					this.SendPropertyChanged("Wall");
					this.OnWallChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoulderRouteVideo")]
	public partial class BoulderRouteVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VideoID;
		
		private string _VideoNo;
		
		private string _Route;
		
		private System.Nullable<bool> _IsDemo;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeletedDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVideoIDChanging(string value);
    partial void OnVideoIDChanged();
    partial void OnVideoNoChanging(string value);
    partial void OnVideoNoChanged();
    partial void OnRouteChanging(string value);
    partial void OnRouteChanged();
    partial void OnIsDemoChanging(System.Nullable<bool> value);
    partial void OnIsDemoChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedDTChanged();
    #endregion
		
		public BoulderRouteVideo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VideoID
		{
			get
			{
				return this._VideoID;
			}
			set
			{
				if ((this._VideoID != value))
				{
					this.OnVideoIDChanging(value);
					this.SendPropertyChanging();
					this._VideoID = value;
					this.SendPropertyChanged("VideoID");
					this.OnVideoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoNo", DbType="VarChar(20)")]
		public string VideoNo
		{
			get
			{
				return this._VideoNo;
			}
			set
			{
				if ((this._VideoNo != value))
				{
					this.OnVideoNoChanging(value);
					this.SendPropertyChanging();
					this._VideoNo = value;
					this.SendPropertyChanged("VideoNo");
					this.OnVideoNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="VarChar(20)")]
		public string Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this.OnRouteChanging(value);
					this.SendPropertyChanging();
					this._Route = value;
					this.SendPropertyChanged("Route");
					this.OnRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDemo", DbType="Bit")]
		public System.Nullable<bool> IsDemo
		{
			get
			{
				return this._IsDemo;
			}
			set
			{
				if ((this._IsDemo != value))
				{
					this.OnIsDemoChanging(value);
					this.SendPropertyChanging();
					this._IsDemo = value;
					this.SendPropertyChanged("IsDemo");
					this.OnIsDemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedDT
		{
			get
			{
				return this._DeletedDT;
			}
			set
			{
				if ((this._DeletedDT != value))
				{
					this.OnDeletedDTChanging(value);
					this.SendPropertyChanging();
					this._DeletedDT = value;
					this.SendPropertyChanged("DeletedDT");
					this.OnDeletedDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rock")]
	public partial class Rock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RockID;
		
		private string _Wall;
		
		private System.Nullable<double> _CoorX;
		
		private System.Nullable<double> _CoorY;
		
		private System.Nullable<double> _CoorZ;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
		private System.Nullable<double> _Radius;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRockIDChanging(string value);
    partial void OnRockIDChanged();
    partial void OnWallChanging(string value);
    partial void OnWallChanged();
    partial void OnCoorXChanging(System.Nullable<double> value);
    partial void OnCoorXChanged();
    partial void OnCoorYChanging(System.Nullable<double> value);
    partial void OnCoorYChanged();
    partial void OnCoorZChanging(System.Nullable<double> value);
    partial void OnCoorZChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    partial void OnRadiusChanging(System.Nullable<double> value);
    partial void OnRadiusChanged();
    #endregion
		
		public Rock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RockID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RockID
		{
			get
			{
				return this._RockID;
			}
			set
			{
				if ((this._RockID != value))
				{
					this.OnRockIDChanging(value);
					this.SendPropertyChanging();
					this._RockID = value;
					this.SendPropertyChanged("RockID");
					this.OnRockIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wall", DbType="VarChar(20)")]
		public string Wall
		{
			get
			{
				return this._Wall;
			}
			set
			{
				if ((this._Wall != value))
				{
					this.OnWallChanging(value);
					this.SendPropertyChanging();
					this._Wall = value;
					this.SendPropertyChanged("Wall");
					this.OnWallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoorX", DbType="Float")]
		public System.Nullable<double> CoorX
		{
			get
			{
				return this._CoorX;
			}
			set
			{
				if ((this._CoorX != value))
				{
					this.OnCoorXChanging(value);
					this.SendPropertyChanging();
					this._CoorX = value;
					this.SendPropertyChanged("CoorX");
					this.OnCoorXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoorY", DbType="Float")]
		public System.Nullable<double> CoorY
		{
			get
			{
				return this._CoorY;
			}
			set
			{
				if ((this._CoorY != value))
				{
					this.OnCoorYChanging(value);
					this.SendPropertyChanging();
					this._CoorY = value;
					this.SendPropertyChanged("CoorY");
					this.OnCoorYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoorZ", DbType="Float")]
		public System.Nullable<double> CoorZ
		{
			get
			{
				return this._CoorZ;
			}
			set
			{
				if ((this._CoorZ != value))
				{
					this.OnCoorZChanging(value);
					this.SendPropertyChanging();
					this._CoorZ = value;
					this.SendPropertyChanged("CoorZ");
					this.OnCoorZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radius", DbType="Float")]
		public System.Nullable<double> Radius
		{
			get
			{
				return this._Radius;
			}
			set
			{
				if ((this._Radius != value))
				{
					this.OnRadiusChanging(value);
					this.SendPropertyChanging();
					this._Radius = value;
					this.SendPropertyChanged("Radius");
					this.OnRadiusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RockOnBoulderRoute")]
	public partial class RockOnBoulderRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RockOnBoulderID;
		
		private string _Rock;
		
		private string _BoulderRoute;
		
		private string _BoulderRockRole;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRockOnBoulderIDChanging(string value);
    partial void OnRockOnBoulderIDChanged();
    partial void OnRockChanging(string value);
    partial void OnRockChanged();
    partial void OnBoulderRouteChanging(string value);
    partial void OnBoulderRouteChanged();
    partial void OnBoulderRockRoleChanging(string value);
    partial void OnBoulderRockRoleChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    #endregion
		
		public RockOnBoulderRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RockOnBoulderID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RockOnBoulderID
		{
			get
			{
				return this._RockOnBoulderID;
			}
			set
			{
				if ((this._RockOnBoulderID != value))
				{
					this.OnRockOnBoulderIDChanging(value);
					this.SendPropertyChanging();
					this._RockOnBoulderID = value;
					this.SendPropertyChanged("RockOnBoulderID");
					this.OnRockOnBoulderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rock", DbType="VarChar(20)")]
		public string Rock
		{
			get
			{
				return this._Rock;
			}
			set
			{
				if ((this._Rock != value))
				{
					this.OnRockChanging(value);
					this.SendPropertyChanging();
					this._Rock = value;
					this.SendPropertyChanged("Rock");
					this.OnRockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoulderRoute", DbType="VarChar(20)")]
		public string BoulderRoute
		{
			get
			{
				return this._BoulderRoute;
			}
			set
			{
				if ((this._BoulderRoute != value))
				{
					this.OnBoulderRouteChanging(value);
					this.SendPropertyChanging();
					this._BoulderRoute = value;
					this.SendPropertyChanged("BoulderRoute");
					this.OnBoulderRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoulderRockRole", DbType="VarChar(10)")]
		public string BoulderRockRole
		{
			get
			{
				return this._BoulderRockRole;
			}
			set
			{
				if ((this._BoulderRockRole != value))
				{
					this.OnBoulderRockRoleChanging(value);
					this.SendPropertyChanging();
					this._BoulderRockRole = value;
					this.SendPropertyChanged("BoulderRockRole");
					this.OnBoulderRockRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RockOnTrainingRoute")]
	public partial class RockOnTrainingRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RockOnTrainingID;
		
		private string _Rock;
		
		private string _TrainingRoute;
		
		private System.Nullable<int> _TrainingRouteSeq;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRockOnTrainingIDChanging(string value);
    partial void OnRockOnTrainingIDChanged();
    partial void OnRockChanging(string value);
    partial void OnRockChanged();
    partial void OnTrainingRouteChanging(string value);
    partial void OnTrainingRouteChanged();
    partial void OnTrainingRouteSeqChanging(System.Nullable<int> value);
    partial void OnTrainingRouteSeqChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    #endregion
		
		public RockOnTrainingRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RockOnTrainingID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RockOnTrainingID
		{
			get
			{
				return this._RockOnTrainingID;
			}
			set
			{
				if ((this._RockOnTrainingID != value))
				{
					this.OnRockOnTrainingIDChanging(value);
					this.SendPropertyChanging();
					this._RockOnTrainingID = value;
					this.SendPropertyChanged("RockOnTrainingID");
					this.OnRockOnTrainingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rock", DbType="VarChar(20)")]
		public string Rock
		{
			get
			{
				return this._Rock;
			}
			set
			{
				if ((this._Rock != value))
				{
					this.OnRockChanging(value);
					this.SendPropertyChanging();
					this._Rock = value;
					this.SendPropertyChanged("Rock");
					this.OnRockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainingRoute", DbType="VarChar(20)")]
		public string TrainingRoute
		{
			get
			{
				return this._TrainingRoute;
			}
			set
			{
				if ((this._TrainingRoute != value))
				{
					this.OnTrainingRouteChanging(value);
					this.SendPropertyChanging();
					this._TrainingRoute = value;
					this.SendPropertyChanged("TrainingRoute");
					this.OnTrainingRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrainingRouteSeq", DbType="Int")]
		public System.Nullable<int> TrainingRouteSeq
		{
			get
			{
				return this._TrainingRouteSeq;
			}
			set
			{
				if ((this._TrainingRouteSeq != value))
				{
					this.OnTrainingRouteSeqChanging(value);
					this.SendPropertyChanging();
					this._TrainingRouteSeq = value;
					this.SendPropertyChanged("TrainingRouteSeq");
					this.OnTrainingRouteSeqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RouteDifficulty")]
	public partial class RouteDifficulty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RouteDifficultyID;
		
		private string _DifficultyDesc;
		
		private System.Nullable<bool> _IsValid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRouteDifficultyIDChanging(string value);
    partial void OnRouteDifficultyIDChanged();
    partial void OnDifficultyDescChanging(string value);
    partial void OnDifficultyDescChanged();
    partial void OnIsValidChanging(System.Nullable<bool> value);
    partial void OnIsValidChanged();
    #endregion
		
		public RouteDifficulty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteDifficultyID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RouteDifficultyID
		{
			get
			{
				return this._RouteDifficultyID;
			}
			set
			{
				if ((this._RouteDifficultyID != value))
				{
					this.OnRouteDifficultyIDChanging(value);
					this.SendPropertyChanging();
					this._RouteDifficultyID = value;
					this.SendPropertyChanged("RouteDifficultyID");
					this.OnRouteDifficultyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DifficultyDesc", DbType="NVarChar(20)")]
		public string DifficultyDesc
		{
			get
			{
				return this._DifficultyDesc;
			}
			set
			{
				if ((this._DifficultyDesc != value))
				{
					this.OnDifficultyDescChanging(value);
					this.SendPropertyChanging();
					this._DifficultyDesc = value;
					this.SendPropertyChanged("DifficultyDesc");
					this.OnDifficultyDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsValid", DbType="Bit")]
		public System.Nullable<bool> IsValid
		{
			get
			{
				return this._IsValid;
			}
			set
			{
				if ((this._IsValid != value))
				{
					this.OnIsValidChanging(value);
					this.SendPropertyChanging();
					this._IsValid = value;
					this.SendPropertyChanged("IsValid");
					this.OnIsValidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrainingRoute")]
	public partial class TrainingRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RouteID;
		
		private string _RouteNo;
		
		private string _Difficulty;
		
		private string _AgeGroup;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
		private string _Wall;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRouteIDChanging(string value);
    partial void OnRouteIDChanged();
    partial void OnRouteNoChanging(string value);
    partial void OnRouteNoChanged();
    partial void OnDifficultyChanging(string value);
    partial void OnDifficultyChanged();
    partial void OnAgeGroupChanging(string value);
    partial void OnAgeGroupChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    partial void OnWallChanging(string value);
    partial void OnWallChanged();
    #endregion
		
		public TrainingRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteNo", DbType="VarChar(20)")]
		public string RouteNo
		{
			get
			{
				return this._RouteNo;
			}
			set
			{
				if ((this._RouteNo != value))
				{
					this.OnRouteNoChanging(value);
					this.SendPropertyChanging();
					this._RouteNo = value;
					this.SendPropertyChanged("RouteNo");
					this.OnRouteNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Difficulty", DbType="VarChar(20)")]
		public string Difficulty
		{
			get
			{
				return this._Difficulty;
			}
			set
			{
				if ((this._Difficulty != value))
				{
					this.OnDifficultyChanging(value);
					this.SendPropertyChanging();
					this._Difficulty = value;
					this.SendPropertyChanged("Difficulty");
					this.OnDifficultyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeGroup", DbType="VarChar(20)")]
		public string AgeGroup
		{
			get
			{
				return this._AgeGroup;
			}
			set
			{
				if ((this._AgeGroup != value))
				{
					this.OnAgeGroupChanging(value);
					this.SendPropertyChanging();
					this._AgeGroup = value;
					this.SendPropertyChanged("AgeGroup");
					this.OnAgeGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wall", DbType="VarChar(20)")]
		public string Wall
		{
			get
			{
				return this._Wall;
			}
			set
			{
				if ((this._Wall != value))
				{
					this.OnWallChanging(value);
					this.SendPropertyChanging();
					this._Wall = value;
					this.SendPropertyChanged("Wall");
					this.OnWallChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrainingRouteVideo")]
	public partial class TrainingRouteVideo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VideoID;
		
		private string _VideoNo;
		
		private string _Route;
		
		private System.Nullable<bool> _IsDemo;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeletedDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVideoIDChanging(string value);
    partial void OnVideoIDChanged();
    partial void OnVideoNoChanging(string value);
    partial void OnVideoNoChanged();
    partial void OnRouteChanging(string value);
    partial void OnRouteChanged();
    partial void OnIsDemoChanging(System.Nullable<bool> value);
    partial void OnIsDemoChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeletedDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedDTChanged();
    #endregion
		
		public TrainingRouteVideo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VideoID
		{
			get
			{
				return this._VideoID;
			}
			set
			{
				if ((this._VideoID != value))
				{
					this.OnVideoIDChanging(value);
					this.SendPropertyChanging();
					this._VideoID = value;
					this.SendPropertyChanged("VideoID");
					this.OnVideoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoNo", DbType="VarChar(20)")]
		public string VideoNo
		{
			get
			{
				return this._VideoNo;
			}
			set
			{
				if ((this._VideoNo != value))
				{
					this.OnVideoNoChanging(value);
					this.SendPropertyChanging();
					this._VideoNo = value;
					this.SendPropertyChanged("VideoNo");
					this.OnVideoNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Route", DbType="VarChar(20)")]
		public string Route
		{
			get
			{
				return this._Route;
			}
			set
			{
				if ((this._Route != value))
				{
					this.OnRouteChanging(value);
					this.SendPropertyChanging();
					this._Route = value;
					this.SendPropertyChanged("Route");
					this.OnRouteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDemo", DbType="Bit")]
		public System.Nullable<bool> IsDemo
		{
			get
			{
				return this._IsDemo;
			}
			set
			{
				if ((this._IsDemo != value))
				{
					this.OnIsDemoChanging(value);
					this.SendPropertyChanging();
					this._IsDemo = value;
					this.SendPropertyChanged("IsDemo");
					this.OnIsDemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedDT
		{
			get
			{
				return this._DeletedDT;
			}
			set
			{
				if ((this._DeletedDT != value))
				{
					this.OnDeletedDTChanging(value);
					this.SendPropertyChanging();
					this._DeletedDT = value;
					this.SendPropertyChanged("DeletedDT");
					this.OnDeletedDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wall")]
	public partial class Wall : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WallID;
		
		private string _WallNo;
		
		private string _WallDesc;
		
		private System.Nullable<System.DateTime> _CreateDT;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _DeleteDT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWallIDChanging(string value);
    partial void OnWallIDChanged();
    partial void OnWallNoChanging(string value);
    partial void OnWallNoChanged();
    partial void OnWallDescChanging(string value);
    partial void OnWallDescChanged();
    partial void OnCreateDTChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDTChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnDeleteDTChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDTChanged();
    #endregion
		
		public Wall()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WallID
		{
			get
			{
				return this._WallID;
			}
			set
			{
				if ((this._WallID != value))
				{
					this.OnWallIDChanging(value);
					this.SendPropertyChanging();
					this._WallID = value;
					this.SendPropertyChanged("WallID");
					this.OnWallIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallNo", DbType="VarChar(20)")]
		public string WallNo
		{
			get
			{
				return this._WallNo;
			}
			set
			{
				if ((this._WallNo != value))
				{
					this.OnWallNoChanging(value);
					this.SendPropertyChanging();
					this._WallNo = value;
					this.SendPropertyChanged("WallNo");
					this.OnWallNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WallDesc", DbType="NVarChar(50)")]
		public string WallDesc
		{
			get
			{
				return this._WallDesc;
			}
			set
			{
				if ((this._WallDesc != value))
				{
					this.OnWallDescChanging(value);
					this.SendPropertyChanging();
					this._WallDesc = value;
					this.SendPropertyChanged("WallDesc");
					this.OnWallDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDT
		{
			get
			{
				return this._CreateDT;
			}
			set
			{
				if ((this._CreateDT != value))
				{
					this.OnCreateDTChanging(value);
					this.SendPropertyChanging();
					this._CreateDT = value;
					this.SendPropertyChanged("CreateDT");
					this.OnCreateDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDT
		{
			get
			{
				return this._DeleteDT;
			}
			set
			{
				if ((this._DeleteDT != value))
				{
					this.OnDeleteDTChanging(value);
					this.SendPropertyChanging();
					this._DeleteDT = value;
					this.SendPropertyChanged("DeleteDT");
					this.OnDeleteDTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
